[project]
name = "nba-player-stats-explorer"
version = "0.1.0"
description = "NBA player statistics exploration and comparison project"
authors = [
    {name = "iamsaturn",email = "arthusjonathan@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "pandas (>=3.0.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)"
]
